server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 40MB
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main/resources
  messages:
    basename: messages
    encoding: UTF-8
  config:
    import:
      optional:file:.env[.properties]
  application:
    name: topichub
    host: localhost
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    listener:
      auto-startup: false
    streams:
      auto-startup: false
  data:
    redis:
      port: ${REDIS_PORT}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  cache:
    type: redis
    cache-names:
        - userDetails
        - tokens
        - hubs
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: web-forum
          service-host-type: ip
        url: http://localhost:8080
application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      accessTokenExpire: 86400000
      refresh-token-expiration: 604800000
logging:
  file:
    name: logs/app/log
    path: logs
  level:
    root: INFO
    web:
      forum:
        topichub: INFO
client:
  hostName:
    ${CLIENT_HOST}
  port:
    ${CLIENT_PORT}
admin:
  hostName:
    ${ADMIN_HOST}
  port:
    ${ADMIN_PORT}
service:
  image:
      uri: ${IMAGE_SERVICE_URL}
